services:
  chatbot:
    build: .
    container_name: chatbot_service
    ports:
      - "8501:8501"
    volumes:
      - ./insurance_new:/app/insurance_new  # Persist ChromaDB storage
    env_file:
      - .env  # Load environment variables